FROM python:3.9-slim

WORKDIR /app

COPY requirements_models.txt requirements.txt
RUN pip install -r requirements.txt

COPY donut/ donut/
COPY ocr/ ocr/
COPY dataset/ dataset/
COPY outputs/ outputs/

CMD ["python", "donut/question_directory.py"]